{% set name = "picobox" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 59d665ee82cafe2de80a6bf9dff407d502bb4688125398eaca05dbe02dbfb07a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools_scm
  run:
    - python >=3.7

test:
  imports:
    - picobox
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/ikalnytskyi/picobox
  summary: Dependency injection framework designed with Python in mind.
  description: |
    Picobox is opinionated dependency injection framework 
    designed to be clean, pragmatic and with Python in mind. 
    No complex graphs, no implicit injections, no type bindings 
    – just picoboxes, and explicit demands!
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://picobox.readthedocs.io
  dev_url: https://github.com/ikalnytskyi/picobox

extra:
  recipe-maintainers:
    - carlodri
