{% set name = "picobox" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 114da1b5606b2f615e8b0eb68d04198ad9de75af5adbcf5b36fe4f664ab927b6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}

test:
  imports:
    - picobox
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/ikalnytskyi/picobox
  summary: Dependency injection framework designed with Python in mind.
  description: |
    Picobox is opinionated dependency injection framework 
    designed to be clean, pragmatic and with Python in mind. 
    No complex graphs, no implicit injections, no type bindings 
    – just picoboxes, and explicit demands!
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://picobox.readthedocs.io
  dev_url: https://github.com/ikalnytskyi/picobox

extra:
  recipe-maintainers:
    - carlodri
